---
title: "education effect"
output: html_document
---

### 최근 학교에 학생 수가 줄어들면서 교사 1인당 학생 수도 줄어들고 있다.
### 교사 1인당 학생 수가 줄어들수록 교육효과는 올라갈 것이라는 가설을 세우고 검증
### 모르겠다를 제외한 지표별로 매우 효과적부터 각각 5,4,3,2,1을 곱하여 평균점수를 계산하여 순위를 책정

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(plotly)
library(corrplot)

load("../satisfaction.rda")

satisfaction %>%
    mutate(교육효과 = (veryGood*5+good*4+normal*3+bad*2+bad*1)/5) %>% 
    rename("교사1인당학생수" = TeaPerStu) %>% 
    ggplot(aes(reorder(state, 교육효과), 교사1인당학생수)) +
    geom_bar(stat = 'identity', mapping = aes(fill=교육효과)) +
    ylab("교사 1인당 학생수") + xlab("시,도별") + 
    coord_flip()  
```

### 교육 효과순으로 정렬하였을 때 교육효과가 높을 수록 교사 1인당 학생수가 적을 것이라고 예측했기 때문에
### 피라미드 모양을 예상했지만 규칙성 없는 그래프를 확인할 수 있음.
### 위 그래프에서 알 수 있듯이 교사 1인당 학생 수와 교육효과는 상관관계가 약해보임.

```{r}
satisfaction %>%
    mutate(교육만족도 = (veryGood*5+good*4+normal*3+bad*2+bad*1)/5) %>% 
    rename("교사1인당학생수" = TeaPerStu) %>% 
    select("교사1인당학생수", "교육만족도") %>% 
    cor() %>% round(2) %>% corrplot(method = "number", tl.srt = 0, tl.col = "blue")
```

### 위 상관계수를 확인해 보면 0.07로 매우 약한 상관관계(사실상 상관관계가 없음)를 확인
### 그럼 혹시 상관관계가 거의 없는 이유가 학원 때문인가?

```{r}
load("../satisfaction_new.rda")

satisfaction_new %>%
    mutate(교육만족도 = (veryGood*5+good*4+normal*3+bad*2+bad*1)/5) %>% 
    rename("인구1000명당사설학원수" = academyper1000) %>% 
    ggplot(aes(reorder(state, 교육만족도), 인구1000명당사설학원수)) +
    geom_bar(stat = 'identity', mapping = aes(fill=교육만족도)) +
    ylab("인구 1000명당 학원 수") + xlab("시,도별") + 
    coord_flip()  

satisfaction_new %>%
    mutate(교육만족도 = (veryGood*5+good*4+normal*3+bad*2+bad*1)/5) %>% 
    rename("인구1000명당사설학원수" = academyper1000) %>% 
    select("인구1000명당사설학원수", "교육만족도") %>% 
    cor() %>% round(2) %>% corrplot(method = "number", tl.srt = 0, tl.col = "blue")
```

### 상관계수가 0.13으로 아주 약한 상관관계가 있음.
